# !!This file must be only used for local development purposes. Do not use it in production!!
version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - gophers-local

  gophers-server:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    env_file:
      - .env
    ports:
      - "${GOPHERS_WEBAPP_PORT}:${GOPHERS_WEBAPP_PORT}"
      - "${GOPHERS_GRPC_SERVER_PORT}:${GOPHERS_GRPC_SERVER_PORT}"
    volumes:
      - ../:/app
    depends_on:
      - mongodb
    networks:
      - gophers-local

volumes:
  mongo_data:

networks:
  gophers-local:
    driver: bridge
